/**
 * LexiGuard AI - Document Exporter & Lawyer Briefing Generator
 * Generates formatted consultation packs, markdown exports, and triggers browser downloads.
 * @module exporter
 */

import { escapeHtml, sanitizeFileName } from '../utils.js';

export class Exporter {
  /**
   * Generates a 1-page structured Lawyer Consultation Preparation Pack.
   * @param {string} docTitle - Document title
   * @param {Object} analysis - Analysis results object
   * @returns {string} Plain-text formatted preparation pack
   */
  generateLawyerConsultPack(docTitle, analysis) {
    const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    const safeTitle = docTitle || 'Legal Contract Document';
    const score = analysis?.riskScore ?? 'N/A';
    const category = analysis?.riskCategory || 'Assessed';
    const summary = analysis?.summary || 'No summary available.';
    const clauses = Array.isArray(analysis?.clauses) ? analysis.clauses : [];

    return `# ==================================================================
# LAWYER CONSULTATION PREPARATION PACK
# Generated by LexiGuard AI | ${today}
# ==================================================================

DOCUMENT ANALYZED: ${safeTitle}
OVERALL RISK PROFILE: ${score}/100 [${category.toUpperCase()}]

------------------------------------------------------------------
1. EXECUTIVE SUMMARY & IDENTIFIED RISKS
------------------------------------------------------------------
${summary}

------------------------------------------------------------------
2. TOP 5 TARGETED QUESTIONS TO ASK YOUR LEGAL COUNSEL:
------------------------------------------------------------------
[ ] 1. Are the restrictive covenants (non-compete / non-solicit) enforceable under state law?
[ ] 2. How can we amend the liability cap or indemnification clause to ensure reciprocal fairness?
[ ] 3. What are the mandatory statutory notice windows for non-renewal in our jurisdiction?
[ ] 4. Can we strike out unilateral amendment clauses or liquidated damages forfeiture?
[ ] 5. What specific amendments or counter-proposal addendums do you recommend prior to signing?

------------------------------------------------------------------
3. FLAGGED RED FLAGS & RISK CLAUSES FOR REVIEW:
------------------------------------------------------------------
${clauses.map((c, i) => `
[ITEM ${i + 1}] Tier: ${c.type.toUpperCase()} | Location: ${c.line}
Title: ${c.title}
Original Snippet: "${c.originalText}"
Plain English Impact: ${c.plainText}
Recommended Revision: ${c.recommendation}
`).join('\n')}

==================================================================
DISCLAIMER: This preparation pack is compiled by an AI document summary
tool for educational and organizational purposes only. It does not
constitute formal legal counsel. Always consult a licensed attorney.
==================================================================`;
  }

  /**
   * Opens a clean printable window formatted for printing or PDF saving.
   * @param {string} docTitle - Document title
   * @param {Object} analysis - Document analysis
   */
  printConsultPack(docTitle, analysis) {
    const printWindow = window.open('', '_blank', 'width=800,height=900');
    if (!printWindow) return;
    try {
      printWindow.opener = null;
    } catch {
      // Ignore if browser restricts opener mutation
    }

    const clauses = Array.isArray(analysis?.clauses) ? analysis.clauses : [];

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Lawyer Consultation Pack — ${escapeHtml(docTitle)}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1e293b; padding: 2.5rem; }
          h1 { font-size: 1.6rem; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; margin-bottom: 0.5rem; }
          .meta-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; margin: 1rem 0 1.5rem 0; }
          .clause-card { border: 1px solid #cbd5e1; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; page-break-inside: avoid; }
          .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; }
          .badge-high { background: #fee2e2; color: #b91c1c; }
          .badge-medium { background: #fef3c7; color: #b45309; }
          .badge-low { background: #dcfce7; color: #15803d; }
          .disclaimer { font-size: 0.75rem; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 1rem; margin-top: 2rem; }
        </style>
      </head>
      <body>
        <h1>LexiGuard AI — Lawyer Consultation Pack</h1>
        <div class="meta-box">
          <strong>Document:</strong> ${escapeHtml(docTitle)}<br/>
          <strong>Risk Score:</strong> ${analysis.riskScore}/100 (${analysis.riskCategory})<br/>
          <strong>Summary:</strong> ${escapeHtml(analysis.summary)}
        </div>

        <h2>Flagged Clauses for Attorney Review</h2>
        ${clauses.map((c, i) => `
          <div class="clause-card">
            <span class="badge badge-${c.type}">${c.type} risk</span> — <strong>${escapeHtml(c.title)}</strong> (${escapeHtml(c.line)})
            <p style="font-family: monospace; font-size: 0.85rem; color: #475569; background: #f1f5f9; padding: 0.5rem; border-radius: 4px;">"${escapeHtml(c.originalText)}"</p>
            <p><strong>Impact:</strong> ${escapeHtml(c.plainText)}</p>
            <p><strong>Proposed Revision:</strong> ${escapeHtml(c.recommendation)}</p>
          </div>
        `).join('')}

        <div class="disclaimer">
          <strong>Disclaimer:</strong> This briefing pack is generated by an automated AI tool for organizational purposes only and does not constitute formal legal advice.
        </div>
      </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 400);
  }

  /**
   * Safely downloads content as a local file with URL revocation to prevent memory leaks.
   * @param {string} filename - Target file name
   * @param {string} content - String content
   * @param {string} [mimeType='text/plain;charset=utf-8'] - MIME type
   */
  downloadFile(filename, content, mimeType = 'text/plain;charset=utf-8') {
    try {
      const safeName = sanitizeFileName(filename, 'document.txt');
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = safeName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (err) {
      console.error('[Exporter] Download failed:', err);
    }
  }
}

export const exporter = new Exporter();
