/**
 * LexiGuard AI - Export & Consultation Pack Generator
 */

export class Exporter {
  /**
   * Generates a 1-page Lawyer Consultation Pack
   */
  generateLawyerConsultPack(docTitle, analysis) {
    const today = new Date().toLocaleDateString();
    
    return `# LAWYER CONSULTATION PREPARATION PACK
Generated by LexiGuard AI | ${today}

------------------------------------------------------------------
DOCUMENT: ${docTitle || 'Legal Document'}
RISK SCORE: ${analysis.riskScore}/100 (${analysis.riskCategory || 'Assessed'})
------------------------------------------------------------------

1. EXECUTIVE SUMMARY & KEY CONCERNS
${analysis.summary}

2. TOP 5 TARGETED QUESTIONS TO ASK YOUR ATTORNEY:
[ ] 1. Are the non-renewal notice requirements and timelines compliant with local consumer/tenant protection laws?
[ ] 2. How can we amend the liability limitation clause to ensure adequate coverage for loss?
[ ] 3. Is the non-compete/non-solicit restrictive scope legally enforceable in our jurisdiction?
[ ] 4. Can we make the legal fee reimbursement provision mutual?
[ ] 5. What specific amendments or counter-proposal addendums do you recommend prior to signing?

3. FLAGGED RED FLAGS & RISK CLAUSES FOR REVIEW:
${analysis.clauses.map((c, i) => `
${i + 1}. [${c.type.toUpperCase()}] ${c.title}
   Clause Location: ${c.line}
   Original Text: "${c.originalText}"
   Plain-English Impact: ${c.plainText}
   Suggested Revision: ${c.recommendation}
`).join('\n')}

------------------------------------------------------------------
DISCLAIMER: This preparation pack is generated by an AI document summary tool for educational and organizational purposes only and does not constitute formal legal counsel. Always consult a licensed attorney.
------------------------------------------------------------------`;
  }

  /**
   * Triggers file download in browser
   */
  downloadFile(filename, content) {
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }
}

export const exporter = new Exporter();
